<a href="https://colab.research.google.com/github/fahim-01/Basic-Pytorch-with-Deep-Learning/blob/main/Basic_Tensor_Operation_and_BackPropagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Basic Tensor operation**

In [1]:
import torch
x=torch.ones(2,3, dtype=torch.double)
print(x.dtype)

torch.float64


In [2]:
x=torch.rand(2,2)
y=torch.rand(2,2)
z= torch.ones(3,4)
w= torch.zeros(3,4)
w.add_(z)
y.sub_(x)
print(y)
print(z)

print(w)

tensor([[-0.3023,  0.2818],
        [-0.0674, -0.1018]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


**BackPropagation**

In [3]:
x = torch.tensor(1.0)
y = torch.tensor(2.0)
w = torch.tensor(1.0, requires_grad=True)

#Forward pass and compute the loss

y_hat = w * x
loss = (y_hat - y)**2

print(loss)

#Backward pass
loss.backward()
print(w.grad)

tensor(1., grad_fn=<PowBackward0>)
tensor(-2.)
